### ISSUE TITLE
Mauvaise direction: Séances > Catégories > Intermédiaire

### ISSUE THREAD

**Issue by martin-jeremy** [larmarange/webin-R#9]
Bonjour,

Merci pour le travail de titan réaliser sur le site Analyse-R et maintenant sur les Webin-R.
Je souhaitais soulevé un problème de redirection et/ou de lien.

Quand on va dans le menu Séance, et qu'on souhaite rechercher les Webin-R enregistré dans la catégorie "Intermédiaire", la page affiché ne comprend pas le caractère spécial 'é' et il n'y a aucune vidéo de proposer.

[https://larmarange.github.io/webin-R/seances.html#category:Intermédiaire](https://larmarange.github.io/webin-R/seances.html#category:Intermédiaire)

![image](https://user-images.githubusercontent.com/65742025/123594006-71b86e80-d7ef-11eb-919e-fc290cd4c47d.png)

Le problème est le même sous Firefox ou Google Chrome. Testé depuis une workstation Ubuntu 20.04.2

**Comment by larmarange** [comment]
En effet, il y a un problème avec les caractères accentués. 

Il faut que je teste la version de développement de distill et que je fasse un retour a l'heure équipe au cas où

**Comment by larmarange** [comment]
Cela devrait être corrigé
